
[[constraint]]
    name = "github.com/hyperledger/fabric"
    branch = "master"
[[constraint]]
    name = "github.com/MediConCenHK/go-chaincode-common"
    branch = "master"
[[override]]
    name = "github.com/fsouza/go-dockerclient"
    version = "=1.2.1"

[[constraint]]
    name = "github.com/davidkhala/goutils"
    branch = "master"
[prune]
  go-tests = true
  unused-packages = true
